### ISSUE TITLE
Feature: Username/Avatar for default client

### ISSUE THREAD

**Issue by scrummer** [LabyMod/discord-webhook-bundle#3]
Add the possibility to set the username and/or avatar (optional) for the default webhook client:
```yaml
discord_webhook:
    webhook_url: 'https://discord.com/my/webhook'
    username: 'Super Bot'
    avatar_url: 'https://url.to/my/cool/avatar'
    # ...
```
